# Generated by Django 6.0 on 2026-05-17 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bd_models', '0015_alter_ballinstance_server_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lootbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, help_text='The name of the lootbox')),
                ('price_multiplier', models.IntegerField(default=1, help_text='The price multiplier for this lootbox; eg. tiers.')),
                ('special_chance', models.IntegerField(default=2, help_text='Chance in percentage to get a special')),
                ('emoji', models.CharField(default='🎁', help_text='The emoji for the lootbox.', max_length=50)),
            ],
            options={
                'verbose_name': 'Lootbox',
                'verbose_name_plural': 'Lootboxes',
            },
        ),
        migrations.CreateModel(
            name='LootSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('economy', models.BooleanField(help_text='Enables economy settings')),
                ('ball_instance_price', models.IntegerField(default=1, help_text='How many balls get sacrificed for a lootbox')),
                ('economy_price', models.IntegerField(default=100, help_text='How much money gets used to obtain a lootbox')),
                ('min_rarity', models.FloatField(default=3.0, help_text='The default rarity where if the collectibles rarity is above then the rig multiplier will apply.')),
                ('rig_multiplier', models.IntegerField(default=1, help_text='The bias towards common balls')),
            ],
            options={
                'verbose_name': 'Lootbox Setting',
                'verbose_name_plural': 'Lootbox Settings',
            },
        ),
        migrations.CreateModel(
            name='PlayerLootbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lootbox', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_lootbox', to='lootboxes.lootbox')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_lootbox', to='bd_models.player')),
            ],
            options={
                'verbose_name': 'Player Lootbox',
                'verbose_name_plural': 'Player Lootboxes',
            },
        ),
    ]
